### Register
POST http://localhost:8000/api/register
Content-Type: application/json

{
    "name": "User3",
    "email": "user3@gmail.com",
    "password": "user3"
}

### Login
POST http://localhost:8000/api/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "user1"
}

################
#### Surveys
################

@token = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImV4cCI6MTYzMTE5OTMyNDI3N30.eyJuYW1lIjoiVXNlcjEiLCJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSJ9.Zrglm6kDtfOxnVBmh-ZXEuJsKNFZli8_aZcFakZbRSu6DkCzWAA9mrpK6kLsZohVUtsklnubLJ0WiewUQi-h7A

### Get all survey for user
GET http://localhost:8000/api/survey
# Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImV4cCI6MTYzMDMxMjA2NzkyMX0.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20ifQ.ewmAyJ1Ce4VSxMXWUM672HJ4oLkkBACVjJ8JXUK2wNgtKIBGtEj11hJfiAIMBCICLDBaS_9LGJFGZZ0JV6Kvyw
Authorization: Bearer {{ token }}

### Get sigle survey
GET http://localhost:8000/api/survey/612e3579ae31846289890e11
Authorization: Bearer {{ token }}

### Create survey
POST http://localhost:8000/api/survey
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "name": "Deno Course",
    "description": "I would like to know your opinion on my Deno course."
}

### Update survey
PUT http://localhost:8000/api/survey/612ca96ea7da0ff27363b7aa
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "name": "Survey1",
    "description": "new description"
}

### Delete survey
DELETE  http://localhost:8000/api/survey/612ca96ea7da0ff27363b7aa
Authorization: Bearer {{ token }}

################
#### Questions
################

### Get all questions for survey
GET http://localhost:8000/api/survey/612e359eae31846289890e12/questions
# Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCIsImV4cCI6MTYzMDMxMjA2NzkyMX0.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20ifQ.ewmAyJ1Ce4VSxMXWUM672HJ4oLkkBACVjJ8JXUK2wNgtKIBGtEj11hJfiAIMBCICLDBaS_9LGJFGZZ0JV6Kvyw
Authorization: Bearer {{ token }}

### Get sigle question
GET http://localhost:8000/api/question/612e04379e4620660df0f5ab
Authorization: Bearer {{ token }}

### Create question
POST http://localhost:8000/api/question/612e35a6ae31846289890e13
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "text": "How much you like TS?",
    "type": "choice",
    "required": true,
    "data": {
        "multiple": false,
        "answers": [
            "I like it very much",
            "I like it",
            "I don't like it",
            "I hate it"
        ]
    }
}

### Update question
PUT http://localhost:8000/api/question/612e04379e4620660df0f5ab
Authorization: Bearer {{ token }}
Content-Type: application/json

{
    "text": "How much you like Node?",
    "type": "choice",
    "required": true,
    "data": {
        "multiple": false,
        "answers": [
            "I like it very much",
            "I like it",
            "I don't like it",
            "I hate it"
        ]
    }
}

### Delete question
DELETE  http://localhost:8000/api/question/612e04379e4620660df0f5ab
Authorization: Bearer {{ token }}